name: 'Allison '
favicon: null
layout_spectrum: 0.8766652110498399
typography_spectrum: 0.4862128682434559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5363610845524818
  lightness: 0.4600047040730715
  saturation: 0.7934907774906605
  rhythmicContrast: 0.7070601598825306
purpose: []
